In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('mentor_eu.csv')
df_ch = pd.read_csv('mentors_students_cleaned.csv')

In [3]:
df.head(5)

,Timestamp,intelligence_type,mentor_role,mentor_career,mentor_skills,session_freq,mentee_attribute,mentee_desired_age,mentee_desired_gender,mentor_age,mentor_gender
0,2021/06/21 8:43:06 pm EET,musical;existential;interpersonal,To support with decision making;To motivate,Sustainability,Communication skills,Once per week ( 15 - 30 minute session),Empathy,17-21,Not relevant,26,Male
1,2021/06/24 11:09:38 am EET,interpersonal,To motivate,Design,Communication skills,Instead of sessions I would prefer weekly e-ma...,Enthusiam,Not relevant,Not relevant,21,Male
2,2021/06/24 1:00:15 pm EET,interpersonal;linguistic,To offer guidance;To motivate,Design,Writing skills,Once per week ( 15 - 30 minute session),Enthusiam,Not relevant,Not relevant,32,Female
3,2021/06/24 1:50:07 pm EET,mathematical;corporal,To motivate;To help to solve problems,Sustainability,Communication skills,Instead of sessions I would prefer weekly e-ma...,Meticulousness,17-21,Not relevant,27,Female
4,2021/06/24 3:33:47 pm EET,existential;interpersonal;corporal,To support with decision making;To help to sol...,Design,Expertise in the field selected in the previou...,Twice per month ( 15 - 30 minute session),Empathy,Not relevant,Not relevant,27,Male

In [4]:
df = df.applymap(lambda s:s.lower() if type(s) == str else s)

In [5]:
df.head(5)

,Timestamp,intelligence_type,mentor_role,mentor_career,mentor_skills,session_freq,mentee_attribute,mentee_desired_age,mentee_desired_gender,mentor_age,mentor_gender
0,2021/06/21 8:43:06 pm eet,musical;existential;interpersonal,to support with decision making;to motivate,sustainability,communication skills,once per week ( 15 - 30 minute session),empathy,17-21,not relevant,26,male
1,2021/06/24 11:09:38 am eet,interpersonal,to motivate,design,communication skills,instead of sessions i would prefer weekly e-ma...,enthusiam,not relevant,not relevant,21,male
2,2021/06/24 1:00:15 pm eet,interpersonal;linguistic,to offer guidance;to motivate,design,writing skills,once per week ( 15 - 30 minute session),enthusiam,not relevant,not relevant,32,female
3,2021/06/24 1:50:07 pm eet,mathematical;corporal,to motivate;to help to solve problems,sustainability,communication skills,instead of sessions i would prefer weekly e-ma...,meticulousness,17-21,not relevant,27,female
4,2021/06/24 3:33:47 pm eet,existential;interpersonal;corporal,to support with decision making;to help to sol...,design,expertise in the field selected in the previou...,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,27,male

In [6]:
df.loc[df['mentor_skills'].str.contains('expertise'), 'mentor_skills'] = 'career know-how'
df.loc[df['mentor_career'].str.contains('resources'), 'mentor_career'] = 'psychology/rrhh'

In [7]:
df.head(18)

,Timestamp,intelligence_type,mentor_role,mentor_career,mentor_skills,session_freq,mentee_attribute,mentee_desired_age,mentee_desired_gender,mentor_age,mentor_gender
0,2021/06/21 8:43:06 pm eet,musical;existential;interpersonal,to support with decision making;to motivate,sustainability,communication skills,once per week ( 15 - 30 minute session),empathy,17-21,not relevant,26,male
1,2021/06/24 11:09:38 am eet,interpersonal,to motivate,design,communication skills,instead of sessions i would prefer weekly e-ma...,enthusiam,not relevant,not relevant,21,male
2,2021/06/24 1:00:15 pm eet,interpersonal;linguistic,to offer guidance;to motivate,design,writing skills,once per week ( 15 - 30 minute session),enthusiam,not relevant,not relevant,32,female
3,2021/06/24 1:50:07 pm eet,mathematical;corporal,to motivate;to help to solve problems,sustainability,communication skills,instead of sessions i would prefer weekly e-ma...,meticulousness,17-21,not relevant,27,female
4,2021/06/24 3:33:47 pm eet,existential;interpersonal;corporal,to support with decision making;to help to sol...,design,career know-how,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,27,male
5,2021/06/25 9:11:51 am eet,natural;corporal;linguistic,to offer guidance;to be accessible to answer q...,marketing,communication skills,once per week ( 15 - 30 minute session),enthusiam,17-21,male,23,female
6,2021/07/26 8:13:00 pm eet,musical;interpersonal;corporal,to support with decision making;to motivate,design,communication skills,twice per month ( 15 - 30 minute session),empathy,27-31,not relevant,30,male
7,2021/07/26 8:19:30 pm eet,interpersonal;intrapersonal,to motivate;to help to solve problems,psychology/rrhh,communication skills,once per month ( 30 - 60 minute session),enthusiam,not relevant,not relevant,27,female
8,2021/07/28 12:42:20 am eet,musical;interpersonal;corporal,to support with decision making;to motivate,design,communication skills,twice per month ( 15 - 30 minute session),empathy,27-31,not relevant,30,male
9,2021/08/07 2:28:04 pm eet,mathematical;interpersonal,to offer guidance,innovation / entrepreneurship,career know-how,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,51,female
10,2021/08/07 2:31:27 pm eet,existential,to offer guidance,information technology,career know-how,once per week ( 15 - 30 minute session),meticulousness,17-21,not relevant,25,male
11,2021/08/07 2:42:16 pm eet,natural;musical,to offer guidance,music,career know-how,twice per month ( 15 - 30 minute session),empathy,22-26,not relevant,62,male
12,2021/08/07 2:43:49 pm eet,linguistic,to motivate;to be accessible to answer questions,art,writing skills,once per week ( 15 - 30 minute session),empathy,not relevant,not relevant,38,female
13,2021/08/07 2:53:03 pm eet,mathematical;existential,to help to solve problems,sustainability,teaching skills,once per month ( 30 - 60 minute session),empathy,22-26,not relevant,32,female
14,2021/08/07 2:53:51 pm eet,mathematical;interpersonal,to help to solve problems,information technology,it skills,once per month ( 30 - 60 minute session),enthusiam,17-21,not relevant,18,female
15,2021/08/07 2:54:40 pm eet,existential;intrapersonal,to be accessible to answer questions,research,communication skills,once per week ( 15 - 30 minute session),modesty,17-21,male,28,male

In [8]:
df_separate = df['intelligence_type'].str.split(';', expand=True)

In [9]:
df_separate.fillna(0)

                0              1              2
0         musical    existential  interpersonal
1   interpersonal              0              0
2   interpersonal     linguistic              0
3    mathematical       corporal              0
4     existential  interpersonal       corporal
5         natural       corporal     linguistic
6         musical  interpersonal       corporal
7   interpersonal  intrapersonal              0
8         musical  interpersonal       corporal
9    mathematical  interpersonal              0
10    existential              0              0
11        natural        musical              0
12     linguistic              0              0
13   mathematical    existential              0
14   mathematical  interpersonal              0
15    existential  intrapersonal              0

In [10]:
df_separate

                0              1              2
0         musical    existential  interpersonal
1   interpersonal           None           None
2   interpersonal     linguistic           None
3    mathematical       corporal           None
4     existential  interpersonal       corporal
5         natural       corporal     linguistic
6         musical  interpersonal       corporal
7   interpersonal  intrapersonal           None
8         musical  interpersonal       corporal
9    mathematical  interpersonal           None
10    existential           None           None
11        natural        musical           None
12     linguistic           None           None
13   mathematical    existential           None
14   mathematical  interpersonal           None
15    existential  intrapersonal           None

In [11]:
df_separate.rename(columns={0: "itype1", 1: "itype2", 2: 'itype3'}, inplace=True)

In [12]:
df_separate

           itype1         itype2         itype3
0         musical    existential  interpersonal
1   interpersonal           None           None
2   interpersonal     linguistic           None
3    mathematical       corporal           None
4     existential  interpersonal       corporal
5         natural       corporal     linguistic
6         musical  interpersonal       corporal
7   interpersonal  intrapersonal           None
8         musical  interpersonal       corporal
9    mathematical  interpersonal           None
10    existential           None           None
11        natural        musical           None
12     linguistic           None           None
13   mathematical    existential           None
14   mathematical  interpersonal           None
15    existential  intrapersonal           None

In [13]:
df1 = pd.concat([df, df_separate], axis=1)

In [14]:
df1.drop(['Timestamp', 'intelligence_type'], axis=1, inplace=True)

In [15]:
df1

,mentor_role,mentor_career,mentor_skills,session_freq,mentee_attribute,mentee_desired_age,mentee_desired_gender,mentor_age,mentor_gender,itype1,itype2,itype3
0,to support with decision making;to motivate,sustainability,communication skills,once per week ( 15 - 30 minute session),empathy,17-21,not relevant,26,male,musical,existential,interpersonal
1,to motivate,design,communication skills,instead of sessions i would prefer weekly e-ma...,enthusiam,not relevant,not relevant,21,male,interpersonal,None,None
2,to offer guidance;to motivate,design,writing skills,once per week ( 15 - 30 minute session),enthusiam,not relevant,not relevant,32,female,interpersonal,linguistic,None
3,to motivate;to help to solve problems,sustainability,communication skills,instead of sessions i would prefer weekly e-ma...,meticulousness,17-21,not relevant,27,female,mathematical,corporal,None
4,to support with decision making;to help to sol...,design,career know-how,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,27,male,existential,interpersonal,corporal
5,to offer guidance;to be accessible to answer q...,marketing,communication skills,once per week ( 15 - 30 minute session),enthusiam,17-21,male,23,female,natural,corporal,linguistic
6,to support with decision making;to motivate,design,communication skills,twice per month ( 15 - 30 minute session),empathy,27-31,not relevant,30,male,musical,interpersonal,corporal
7,to motivate;to help to solve problems,psychology/rrhh,communication skills,once per month ( 30 - 60 minute session),enthusiam,not relevant,not relevant,27,female,interpersonal,intrapersonal,None
8,to support with decision making;to motivate,design,communication skills,twice per month ( 15 - 30 minute session),empathy,27-31,not relevant,30,male,musical,interpersonal,corporal
9,to offer guidance,innovation / entrepreneurship,career know-how,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,51,female,mathematical,interpersonal,None
10,to offer guidance,information technology,career know-how,once per week ( 15 - 30 minute session),meticulousness,17-21,not relevant,25,male,existential,None,None
11,to offer guidance,music,career know-how,twice per month ( 15 - 30 minute session),empathy,22-26,not relevant,62,male,natural,musical,None
12,to motivate;to be accessible to answer questions,art,writing skills,once per week ( 15 - 30 minute session),empathy,not relevant,not relevant,38,female,linguistic,None,None
13,to help to solve problems,sustainability,teaching skills,once per month ( 30 - 60 minute session),empathy,22-26,not relevant,32,female,mathematical,existential,None
14,to help to solve problems,information technology,it skills,once per month ( 30 - 60 minute session),enthusiam,17-21,not relevant,18,female,mathematical,interpersonal,None
15,to be accessible to answer questions,research,communication skills,once per week ( 15 - 30 minute session),modesty,17-21,male,28,male,existential,intrapersonal,None

In [16]:
df_role = df1['mentor_role'].str.split(';', expand=True)
df_role

                                       0                                     1
0        to support with decision making                           to motivate
1                            to motivate                                  None
2                      to offer guidance                           to motivate
3                            to motivate             to help to solve problems
4        to support with decision making             to help to solve problems
5                      to offer guidance  to be accessible to answer questions
6        to support with decision making                           to motivate
7                            to motivate             to help to solve problems
8        to support with decision making                           to motivate
9                      to offer guidance                                  None
10                     to offer guidance                                  None
11                     to offer guidance                                  None
12                           to motivate  to be accessible to answer questions
13             to help to solve problems                                  None
14             to help to solve problems                                  None
15  to be accessible to answer questions                                  None

In [17]:
df_role.rename(columns={0: "itype4", 1: "itype5"}, inplace=True)
df_role.fillna(0)

                                  itype4                                itype5
0        to support with decision making                           to motivate
1                            to motivate                                     0
2                      to offer guidance                           to motivate
3                            to motivate             to help to solve problems
4        to support with decision making             to help to solve problems
5                      to offer guidance  to be accessible to answer questions
6        to support with decision making                           to motivate
7                            to motivate             to help to solve problems
8        to support with decision making                           to motivate
9                      to offer guidance                                     0
10                     to offer guidance                                     0
11                     to offer guidance                                     0
12                           to motivate  to be accessible to answer questions
13             to help to solve problems                                     0
14             to help to solve problems                                     0
15  to be accessible to answer questions                                     0

In [18]:
df_role.loc[df_role['itype4'].str.contains('solve') ==True, 'itype4'] = 'solve_problems'
df_role.loc[df_role['itype5'].str.contains('solve') ==True, 'itype5'] = 'solve_problems'
df_role.loc[df_role['itype4'].str.contains('support') ==True, 'itype4'] = 'support'
df_role.loc[df_role['itype5'].str.contains('support') ==True, 'itype5'] = 'support'
df_role.loc[df_role['itype4'].str.contains('accessible') ==True, 'itype4'] = 'availability'
df_role.loc[df_role['itype5'].str.contains('accessible') ==True, 'itype5'] = 'availability'
df_role.loc[df_role['itype4'].str.contains('guidance') ==True, 'itype4'] = 'guidance'
df_role.loc[df_role['itype5'].str.contains('guidance') ==True, 'itype5'] = 'guidance'
df_role.loc[df_role['itype4'].str.contains('motivate') ==True, 'itype4'] = 'motivate'
df_role.loc[df_role['itype5'].str.contains('motivate') ==True, 'itype5'] = 'motivate'

In [19]:
df_role

            itype4          itype5
0          support        motivate
1         motivate            None
2         guidance        motivate
3         motivate  solve_problems
4          support  solve_problems
5         guidance    availability
6          support        motivate
7         motivate  solve_problems
8          support        motivate
9         guidance            None
10        guidance            None
11        guidance            None
12        motivate    availability
13  solve_problems            None
14  solve_problems            None
15    availability            None

In [20]:
df_final = pd.concat([df1, df_role], axis=1)
df_final.drop(['mentor_role'], axis=1, inplace=True)

In [21]:
df_final

,mentor_career,mentor_skills,session_freq,mentee_attribute,mentee_desired_age,mentee_desired_gender,mentor_age,mentor_gender,itype1,itype2,itype3,itype4,itype5
0,sustainability,communication skills,once per week ( 15 - 30 minute session),empathy,17-21,not relevant,26,male,musical,existential,interpersonal,support,motivate
1,design,communication skills,instead of sessions i would prefer weekly e-ma...,enthusiam,not relevant,not relevant,21,male,interpersonal,None,None,motivate,None
2,design,writing skills,once per week ( 15 - 30 minute session),enthusiam,not relevant,not relevant,32,female,interpersonal,linguistic,None,guidance,motivate
3,sustainability,communication skills,instead of sessions i would prefer weekly e-ma...,meticulousness,17-21,not relevant,27,female,mathematical,corporal,None,motivate,solve_problems
4,design,career know-how,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,27,male,existential,interpersonal,corporal,support,solve_problems
5,marketing,communication skills,once per week ( 15 - 30 minute session),enthusiam,17-21,male,23,female,natural,corporal,linguistic,guidance,availability
6,design,communication skills,twice per month ( 15 - 30 minute session),empathy,27-31,not relevant,30,male,musical,interpersonal,corporal,support,motivate
7,psychology/rrhh,communication skills,once per month ( 30 - 60 minute session),enthusiam,not relevant,not relevant,27,female,interpersonal,intrapersonal,None,motivate,solve_problems
8,design,communication skills,twice per month ( 15 - 30 minute session),empathy,27-31,not relevant,30,male,musical,interpersonal,corporal,support,motivate
9,innovation / entrepreneurship,career know-how,twice per month ( 15 - 30 minute session),empathy,not relevant,not relevant,51,female,mathematical,interpersonal,None,guidance,None
10,information technology,career know-how,once per week ( 15 - 30 minute session),meticulousness,17-21,not relevant,25,male,existential,None,None,guidance,None
11,music,career know-how,twice per month ( 15 - 30 minute session),empathy,22-26,not relevant,62,male,natural,musical,None,guidance,None
12,art,writing skills,once per week ( 15 - 30 minute session),empathy,not relevant,not relevant,38,female,linguistic,None,None,motivate,availability
13,sustainability,teaching skills,once per month ( 30 - 60 minute session),empathy,22-26,not relevant,32,female,mathematical,existential,None,solve_problems,None
14,information technology,it skills,once per month ( 30 - 60 minute session),enthusiam,17-21,not relevant,18,female,mathematical,interpersonal,None,solve_problems,None
15,research,communication skills,once per week ( 15 - 30 minute session),modesty,17-21,male,28,male,existential,intrapersonal,None,availability,None

In [22]:
#rename columns
df_final.rename(columns={"itype4": "mentor_rol_1", "itype5": "mentor_rol_2"}, inplace=True)
df_final.loc[df_final['mentor_career'].str.contains('technology'), 'mentor_career'] = 'it'
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   mentor_career          16 non-null     object
 1   mentor_skills          16 non-null     object
 2   session_freq           16 non-null     object
 3   mentee_attribute       16 non-null     object
 4   mentee_desired_age     16 non-null     object
 5   mentee_desired_gender  16 non-null     object
 6   mentor_age             16 non-null     int64
 7   mentor_gender          16 non-null     object
 8   itype1                 16 non-null     object
 9   itype2                 13 non-null     object
 10  itype3                 5 non-null      object
 11  mentor_rol_1           16 non-null     object
 12  mentor_rol_2           9 non-null      object
dtypes: int64(1), object(12)
memory usage: 1.8+ KB

In [23]:
# QUICK ROUND OF CHECKING ALL VALUES BEFORE EXPORTING DATASET TO BE JOINED TO ADDITIONAL 2 others

In [24]:
df_final['itype1'].value_counts()

mathematical     4
existential      3
interpersonal    3
musical          3
natural          2
linguistic       1
Name: itype1, dtype: int64

In [25]:
df_final['itype2'].value_counts()

interpersonal    5
existential      2
intrapersonal    2
corporal         2
linguistic       1
musical          1
Name: itype2, dtype: int64

In [26]:
df_final['itype3'].value_counts()

corporal         3
interpersonal    1
linguistic       1
Name: itype3, dtype: int64

In [27]:
df_final['mentee_attribute'].value_counts()

empathy           8
enthusiam         5
meticulousness    2
modesty           1
Name: mentee_attribute, dtype: int64

In [28]:
df_final['mentor_career'].value_counts()

design                           5
sustainability                   3
it                               2
psychology/rrhh                  1
innovation / entrepreneurship    1
marketing                        1
research                         1
art                              1
music                            1
Name: mentor_career, dtype: int64

In [29]:
df_final['mentor_skills'].value_counts()

communication skills    8
career know-how         4
writing skills          2
it skills               1
teaching skills         1
Name: mentor_skills, dtype: int64

In [30]:
df_final['session_freq'].value_counts()

once per week ( 15 - 30 minute session)                           6
twice per month ( 15 - 30 minute session)                         5
once per month ( 30 - 60 minute session)                          3
instead of sessions i would prefer weekly e-mail communication    2
Name: session_freq, dtype: int64

In [31]:
df_final.to_csv('mentors_eu_cleaned.csv')